// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.pingan.traffic.protocol;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.CcRequest.Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.CcRequest.Header header = 1;</code>
     */
    com.pingan.traffic.protocol.Protocol.CcRequest.Header getHeader();
    /**
     * <code>.CcRequest.Header header = 1;</code>
     */
    com.pingan.traffic.protocol.Protocol.CcRequest.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>string body = 2;</code>
     */
    java.lang.String getBody();
    /**
     * <code>string body = 2;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();
  }
  /**
   * <pre>
   *请求消息体
   * </pre>
   *
   * Protobuf type {@code CcRequest}
   */
  public  static final class CcRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CcRequest)
      CcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CcRequest.newBuilder() to construct.
    private CcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CcRequest() {
      body_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.pingan.traffic.protocol.Protocol.CcRequest.Header.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.pingan.traffic.protocol.Protocol.CcRequest.Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pingan.traffic.protocol.Protocol.internal_static_CcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pingan.traffic.protocol.Protocol.internal_static_CcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pingan.traffic.protocol.Protocol.CcRequest.class, com.pingan.traffic.protocol.Protocol.CcRequest.Builder.class);
    }

    public interface HeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CcRequest.Header)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       *head id
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      int getId();

      /**
       * <pre>
       * 消息码(0:成功，其他:错误)
       * </pre>
       *
       * <code>int32 code = 2;</code>
       */
      int getCode();

      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string msg = 3;</code>
       */
      java.lang.String getMsg();
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string msg = 3;</code>
       */
      com.google.protobuf.ByteString
          getMsgBytes();
    }
    /**
     * Protobuf type {@code CcRequest.Header}
     */
    public  static final class Header extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CcRequest.Header)
        HeaderOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Header.newBuilder() to construct.
      private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Header() {
        id_ = 0;
        code_ = 0;
        msg_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Header(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                id_ = input.readInt32();
                break;
              }
              case 16: {

                code_ = input.readInt32();
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                msg_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pingan.traffic.protocol.Protocol.internal_static_CcRequest_Header_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pingan.traffic.protocol.Protocol.internal_static_CcRequest_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pingan.traffic.protocol.Protocol.CcRequest.Header.class, com.pingan.traffic.protocol.Protocol.CcRequest.Header.Builder.class);
      }

      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <pre>
       *head id
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      public static final int CODE_FIELD_NUMBER = 2;
      private int code_;
      /**
       * <pre>
       * 消息码(0:成功，其他:错误)
       * </pre>
       *
       * <code>int32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }

      public static final int MSG_FIELD_NUMBER = 3;
      private volatile java.lang.Object msg_;
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string msg = 3;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (id_ != 0) {
          output.writeInt32(1, id_);
        }
        if (code_ != 0) {
          output.writeInt32(2, code_);
        }
        if (!getMsgBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (code_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, code_);
        }
        if (!getMsgBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.pingan.traffic.protocol.Protocol.CcRequest.Header)) {
          return super.equals(obj);
        }
        com.pingan.traffic.protocol.Protocol.CcRequest.Header other = (com.pingan.traffic.protocol.Protocol.CcRequest.Header) obj;

        boolean result = true;
        result = result && (getId()
            == other.getId());
        result = result && (getCode()
            == other.getCode());
        result = result && getMsg()
            .equals(other.getMsg());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.pingan.traffic.protocol.Protocol.CcRequest.Header prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CcRequest.Header}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CcRequest.Header)
          com.pingan.traffic.protocol.Protocol.CcRequest.HeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.pingan.traffic.protocol.Protocol.internal_static_CcRequest_Header_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.pingan.traffic.protocol.Protocol.internal_static_CcRequest_Header_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.pingan.traffic.protocol.Protocol.CcRequest.Header.class, com.pingan.traffic.protocol.Protocol.CcRequest.Header.Builder.class);
        }

        // Construct using com.pingan.traffic.protocol.Protocol.CcRequest.Header.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = 0;

          code_ = 0;

          msg_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.pingan.traffic.protocol.Protocol.internal_static_CcRequest_Header_descriptor;
        }

        @java.lang.Override
        public com.pingan.traffic.protocol.Protocol.CcRequest.Header getDefaultInstanceForType() {
          return com.pingan.traffic.protocol.Protocol.CcRequest.Header.getDefaultInstance();
        }

        @java.lang.Override
        public com.pingan.traffic.protocol.Protocol.CcRequest.Header build() {
          com.pingan.traffic.protocol.Protocol.CcRequest.Header result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.pingan.traffic.protocol.Protocol.CcRequest.Header buildPartial() {
          com.pingan.traffic.protocol.Protocol.CcRequest.Header result = new com.pingan.traffic.protocol.Protocol.CcRequest.Header(this);
          result.id_ = id_;
          result.code_ = code_;
          result.msg_ = msg_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.pingan.traffic.protocol.Protocol.CcRequest.Header) {
            return mergeFrom((com.pingan.traffic.protocol.Protocol.CcRequest.Header)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.pingan.traffic.protocol.Protocol.CcRequest.Header other) {
          if (other == com.pingan.traffic.protocol.Protocol.CcRequest.Header.getDefaultInstance()) return this;
          if (other.getId() != 0) {
            setId(other.getId());
          }
          if (other.getCode() != 0) {
            setCode(other.getCode());
          }
          if (!other.getMsg().isEmpty()) {
            msg_ = other.msg_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.pingan.traffic.protocol.Protocol.CcRequest.Header parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.pingan.traffic.protocol.Protocol.CcRequest.Header) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int id_ ;
        /**
         * <pre>
         *head id
         * </pre>
         *
         * <code>int32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <pre>
         *head id
         * </pre>
         *
         * <code>int32 id = 1;</code>
         */
        public Builder setId(int value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *head id
         * </pre>
         *
         * <code>int32 id = 1;</code>
         */
        public Builder clearId() {
          
          id_ = 0;
          onChanged();
          return this;
        }

        private int code_ ;
        /**
         * <pre>
         * 消息码(0:成功，其他:错误)
         * </pre>
         *
         * <code>int32 code = 2;</code>
         */
        public int getCode() {
          return code_;
        }
        /**
         * <pre>
         * 消息码(0:成功，其他:错误)
         * </pre>
         *
         * <code>int32 code = 2;</code>
         */
        public Builder setCode(int value) {
          
          code_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 消息码(0:成功，其他:错误)
         * </pre>
         *
         * <code>int32 code = 2;</code>
         */
        public Builder clearCode() {
          
          code_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object msg_ = "";
        /**
         * <pre>
         * 消息内容
         * </pre>
         *
         * <code>string msg = 3;</code>
         */
        public java.lang.String getMsg() {
          java.lang.Object ref = msg_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            msg_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * 消息内容
         * </pre>
         *
         * <code>string msg = 3;</code>
         */
        public com.google.protobuf.ByteString
            getMsgBytes() {
          java.lang.Object ref = msg_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            msg_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 消息内容
         * </pre>
         *
         * <code>string msg = 3;</code>
         */
        public Builder setMsg(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          msg_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 消息内容
         * </pre>
         *
         * <code>string msg = 3;</code>
         */
        public Builder clearMsg() {
          
          msg_ = getDefaultInstance().getMsg();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 消息内容
         * </pre>
         *
         * <code>string msg = 3;</code>
         */
        public Builder setMsgBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          msg_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:CcRequest.Header)
      }

      // @@protoc_insertion_point(class_scope:CcRequest.Header)
      private static final com.pingan.traffic.protocol.Protocol.CcRequest.Header DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.pingan.traffic.protocol.Protocol.CcRequest.Header();
      }

      public static com.pingan.traffic.protocol.Protocol.CcRequest.Header getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Header>
          PARSER = new com.google.protobuf.AbstractParser<Header>() {
        @java.lang.Override
        public Header parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Header(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Header> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Header> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.pingan.traffic.protocol.Protocol.CcRequest.Header getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.pingan.traffic.protocol.Protocol.CcRequest.Header header_;
    /**
     * <code>.CcRequest.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.CcRequest.Header header = 1;</code>
     */
    public com.pingan.traffic.protocol.Protocol.CcRequest.Header getHeader() {
      return header_ == null ? com.pingan.traffic.protocol.Protocol.CcRequest.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.CcRequest.Header header = 1;</code>
     */
    public com.pingan.traffic.protocol.Protocol.CcRequest.HeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private volatile java.lang.Object body_;
    /**
     * <code>string body = 2;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pingan.traffic.protocol.Protocol.CcRequest)) {
        return super.equals(obj);
      }
      com.pingan.traffic.protocol.Protocol.CcRequest other = (com.pingan.traffic.protocol.Protocol.CcRequest) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && getBody()
          .equals(other.getBody());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pingan.traffic.protocol.Protocol.CcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pingan.traffic.protocol.Protocol.CcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pingan.traffic.protocol.Protocol.CcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pingan.traffic.protocol.Protocol.CcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pingan.traffic.protocol.Protocol.CcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pingan.traffic.protocol.Protocol.CcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pingan.traffic.protocol.Protocol.CcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pingan.traffic.protocol.Protocol.CcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pingan.traffic.protocol.Protocol.CcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pingan.traffic.protocol.Protocol.CcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pingan.traffic.protocol.Protocol.CcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pingan.traffic.protocol.Protocol.CcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pingan.traffic.protocol.Protocol.CcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求消息体
     * </pre>
     *
     * Protobuf type {@code CcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CcRequest)
        com.pingan.traffic.protocol.Protocol.CcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pingan.traffic.protocol.Protocol.internal_static_CcRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pingan.traffic.protocol.Protocol.internal_static_CcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pingan.traffic.protocol.Protocol.CcRequest.class, com.pingan.traffic.protocol.Protocol.CcRequest.Builder.class);
      }

      // Construct using com.pingan.traffic.protocol.Protocol.CcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        body_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pingan.traffic.protocol.Protocol.internal_static_CcRequest_descriptor;
      }

      @java.lang.Override
      public com.pingan.traffic.protocol.Protocol.CcRequest getDefaultInstanceForType() {
        return com.pingan.traffic.protocol.Protocol.CcRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.pingan.traffic.protocol.Protocol.CcRequest build() {
        com.pingan.traffic.protocol.Protocol.CcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.pingan.traffic.protocol.Protocol.CcRequest buildPartial() {
        com.pingan.traffic.protocol.Protocol.CcRequest result = new com.pingan.traffic.protocol.Protocol.CcRequest(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pingan.traffic.protocol.Protocol.CcRequest) {
          return mergeFrom((com.pingan.traffic.protocol.Protocol.CcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pingan.traffic.protocol.Protocol.CcRequest other) {
        if (other == com.pingan.traffic.protocol.Protocol.CcRequest.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pingan.traffic.protocol.Protocol.CcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pingan.traffic.protocol.Protocol.CcRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.pingan.traffic.protocol.Protocol.CcRequest.Header header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pingan.traffic.protocol.Protocol.CcRequest.Header, com.pingan.traffic.protocol.Protocol.CcRequest.Header.Builder, com.pingan.traffic.protocol.Protocol.CcRequest.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.CcRequest.Header header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.CcRequest.Header header = 1;</code>
       */
      public com.pingan.traffic.protocol.Protocol.CcRequest.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.pingan.traffic.protocol.Protocol.CcRequest.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.CcRequest.Header header = 1;</code>
       */
      public Builder setHeader(com.pingan.traffic.protocol.Protocol.CcRequest.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CcRequest.Header header = 1;</code>
       */
      public Builder setHeader(
          com.pingan.traffic.protocol.Protocol.CcRequest.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CcRequest.Header header = 1;</code>
       */
      public Builder mergeHeader(com.pingan.traffic.protocol.Protocol.CcRequest.Header value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.pingan.traffic.protocol.Protocol.CcRequest.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CcRequest.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CcRequest.Header header = 1;</code>
       */
      public com.pingan.traffic.protocol.Protocol.CcRequest.Header.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.CcRequest.Header header = 1;</code>
       */
      public com.pingan.traffic.protocol.Protocol.CcRequest.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.pingan.traffic.protocol.Protocol.CcRequest.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.CcRequest.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pingan.traffic.protocol.Protocol.CcRequest.Header, com.pingan.traffic.protocol.Protocol.CcRequest.Header.Builder, com.pingan.traffic.protocol.Protocol.CcRequest.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.pingan.traffic.protocol.Protocol.CcRequest.Header, com.pingan.traffic.protocol.Protocol.CcRequest.Header.Builder, com.pingan.traffic.protocol.Protocol.CcRequest.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>string body = 2;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string body = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 2;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 2;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 2;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CcRequest)
    }

    // @@protoc_insertion_point(class_scope:CcRequest)
    private static final com.pingan.traffic.protocol.Protocol.CcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pingan.traffic.protocol.Protocol.CcRequest();
    }

    public static com.pingan.traffic.protocol.Protocol.CcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CcRequest>
        PARSER = new com.google.protobuf.AbstractParser<CcRequest>() {
      @java.lang.Override
      public CcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CcRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CcRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CcRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.pingan.traffic.protocol.Protocol.CcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CcRequest_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CcRequest_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocol.proto\"m\n\tCcRequest\022!\n\006header\030" +
      "\001 \001(\0132\021.CcRequest.Header\022\014\n\004body\030\002 \001(\t\032/" +
      "\n\006Header\022\n\n\002id\030\001 \001(\005\022\014\n\004code\030\002 \001(\005\022\013\n\003ms" +
      "g\030\003 \001(\tB\'\n\033com.pingan.traffic.protocolB\010" +
      "Protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CcRequest_descriptor,
        new java.lang.String[] { "Header", "Body", });
    internal_static_CcRequest_Header_descriptor =
      internal_static_CcRequest_descriptor.getNestedTypes().get(0);
    internal_static_CcRequest_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CcRequest_Header_descriptor,
        new java.lang.String[] { "Id", "Code", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
