// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolModule.proto

package com.pingan.traffic.protocol;

public final class ProtocolModule {
  private ProtocolModule() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommonProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommonProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
     */
    boolean hasReqHeader();
    /**
     * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
     */
    com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader getReqHeader();
    /**
     * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
     */
    com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeaderOrBuilder getReqHeaderOrBuilder();

    /**
     * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
     */
    boolean hasResHeader();
    /**
     * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
     */
    com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader getResHeader();
    /**
     * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
     */
    com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeaderOrBuilder getResHeaderOrBuilder();

    /**
     * <code>string data = 3;</code>
     */
    java.lang.String getData();
    /**
     * <code>string data = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * <pre>
   *公共头
   * </pre>
   *
   * Protobuf type {@code CommonProtocol}
   */
  public  static final class CommonProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommonProtocol)
      CommonProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommonProtocol.newBuilder() to construct.
    private CommonProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommonProtocol() {
      data_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommonProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.Builder subBuilder = null;
              if (reqHeader_ != null) {
                subBuilder = reqHeader_.toBuilder();
              }
              reqHeader_ = input.readMessage(com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(reqHeader_);
                reqHeader_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.Builder subBuilder = null;
              if (resHeader_ != null) {
                subBuilder = resHeader_.toBuilder();
              }
              resHeader_ = input.readMessage(com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resHeader_);
                resHeader_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.class, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.Builder.class);
    }

    public interface RequestHeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CommonProtocol.RequestHeader)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 id = 1;</code>
       */
      int getId();

      /**
       * <code>int32 code = 2;</code>
       */
      int getCode();

      /**
       * <code>string msg = 3;</code>
       */
      java.lang.String getMsg();
      /**
       * <code>string msg = 3;</code>
       */
      com.google.protobuf.ByteString
          getMsgBytes();
    }
    /**
     * Protobuf type {@code CommonProtocol.RequestHeader}
     */
    public  static final class RequestHeader extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CommonProtocol.RequestHeader)
        RequestHeaderOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use RequestHeader.newBuilder() to construct.
      private RequestHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private RequestHeader() {
        id_ = 0;
        code_ = 0;
        msg_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private RequestHeader(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                id_ = input.readInt32();
                break;
              }
              case 16: {

                code_ = input.readInt32();
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                msg_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_RequestHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_RequestHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.class, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.Builder.class);
      }

      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      public static final int CODE_FIELD_NUMBER = 2;
      private int code_;
      /**
       * <code>int32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }

      public static final int MSG_FIELD_NUMBER = 3;
      private volatile java.lang.Object msg_;
      /**
       * <code>string msg = 3;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        }
      }
      /**
       * <code>string msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (id_ != 0) {
          output.writeInt32(1, id_);
        }
        if (code_ != 0) {
          output.writeInt32(2, code_);
        }
        if (!getMsgBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (code_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, code_);
        }
        if (!getMsgBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader)) {
          return super.equals(obj);
        }
        com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader other = (com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader) obj;

        boolean result = true;
        result = result && (getId()
            == other.getId());
        result = result && (getCode()
            == other.getCode());
        result = result && getMsg()
            .equals(other.getMsg());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CommonProtocol.RequestHeader}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CommonProtocol.RequestHeader)
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_RequestHeader_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_RequestHeader_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.class, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.Builder.class);
        }

        // Construct using com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = 0;

          code_ = 0;

          msg_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_RequestHeader_descriptor;
        }

        @java.lang.Override
        public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader getDefaultInstanceForType() {
          return com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.getDefaultInstance();
        }

        @java.lang.Override
        public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader build() {
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader buildPartial() {
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader result = new com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader(this);
          result.id_ = id_;
          result.code_ = code_;
          result.msg_ = msg_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader) {
            return mergeFrom((com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader other) {
          if (other == com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.getDefaultInstance()) return this;
          if (other.getId() != 0) {
            setId(other.getId());
          }
          if (other.getCode() != 0) {
            setCode(other.getCode());
          }
          if (!other.getMsg().isEmpty()) {
            msg_ = other.msg_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int id_ ;
        /**
         * <code>int32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>int32 id = 1;</code>
         */
        public Builder setId(int value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 id = 1;</code>
         */
        public Builder clearId() {
          
          id_ = 0;
          onChanged();
          return this;
        }

        private int code_ ;
        /**
         * <code>int32 code = 2;</code>
         */
        public int getCode() {
          return code_;
        }
        /**
         * <code>int32 code = 2;</code>
         */
        public Builder setCode(int value) {
          
          code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 code = 2;</code>
         */
        public Builder clearCode() {
          
          code_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object msg_ = "";
        /**
         * <code>string msg = 3;</code>
         */
        public java.lang.String getMsg() {
          java.lang.Object ref = msg_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            msg_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string msg = 3;</code>
         */
        public com.google.protobuf.ByteString
            getMsgBytes() {
          java.lang.Object ref = msg_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            msg_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string msg = 3;</code>
         */
        public Builder setMsg(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          msg_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string msg = 3;</code>
         */
        public Builder clearMsg() {
          
          msg_ = getDefaultInstance().getMsg();
          onChanged();
          return this;
        }
        /**
         * <code>string msg = 3;</code>
         */
        public Builder setMsgBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          msg_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:CommonProtocol.RequestHeader)
      }

      // @@protoc_insertion_point(class_scope:CommonProtocol.RequestHeader)
      private static final com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader();
      }

      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<RequestHeader>
          PARSER = new com.google.protobuf.AbstractParser<RequestHeader>() {
        @java.lang.Override
        public RequestHeader parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestHeader(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<RequestHeader> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<RequestHeader> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface ResponseHeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CommonProtocol.ResponseHeader)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 id = 1;</code>
       */
      int getId();

      /**
       * <code>int32 code = 2;</code>
       */
      int getCode();

      /**
       * <code>string msg = 3;</code>
       */
      java.lang.String getMsg();
      /**
       * <code>string msg = 3;</code>
       */
      com.google.protobuf.ByteString
          getMsgBytes();
    }
    /**
     * Protobuf type {@code CommonProtocol.ResponseHeader}
     */
    public  static final class ResponseHeader extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CommonProtocol.ResponseHeader)
        ResponseHeaderOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ResponseHeader.newBuilder() to construct.
      private ResponseHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ResponseHeader() {
        id_ = 0;
        code_ = 0;
        msg_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ResponseHeader(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                id_ = input.readInt32();
                break;
              }
              case 16: {

                code_ = input.readInt32();
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                msg_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_ResponseHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_ResponseHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.class, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.Builder.class);
      }

      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      public static final int CODE_FIELD_NUMBER = 2;
      private int code_;
      /**
       * <code>int32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }

      public static final int MSG_FIELD_NUMBER = 3;
      private volatile java.lang.Object msg_;
      /**
       * <code>string msg = 3;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        }
      }
      /**
       * <code>string msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (id_ != 0) {
          output.writeInt32(1, id_);
        }
        if (code_ != 0) {
          output.writeInt32(2, code_);
        }
        if (!getMsgBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (code_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, code_);
        }
        if (!getMsgBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader)) {
          return super.equals(obj);
        }
        com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader other = (com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader) obj;

        boolean result = true;
        result = result && (getId()
            == other.getId());
        result = result && (getCode()
            == other.getCode());
        result = result && getMsg()
            .equals(other.getMsg());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CommonProtocol.ResponseHeader}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CommonProtocol.ResponseHeader)
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_ResponseHeader_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_ResponseHeader_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.class, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.Builder.class);
        }

        // Construct using com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = 0;

          code_ = 0;

          msg_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_ResponseHeader_descriptor;
        }

        @java.lang.Override
        public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader getDefaultInstanceForType() {
          return com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.getDefaultInstance();
        }

        @java.lang.Override
        public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader build() {
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader buildPartial() {
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader result = new com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader(this);
          result.id_ = id_;
          result.code_ = code_;
          result.msg_ = msg_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader) {
            return mergeFrom((com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader other) {
          if (other == com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.getDefaultInstance()) return this;
          if (other.getId() != 0) {
            setId(other.getId());
          }
          if (other.getCode() != 0) {
            setCode(other.getCode());
          }
          if (!other.getMsg().isEmpty()) {
            msg_ = other.msg_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int id_ ;
        /**
         * <code>int32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>int32 id = 1;</code>
         */
        public Builder setId(int value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 id = 1;</code>
         */
        public Builder clearId() {
          
          id_ = 0;
          onChanged();
          return this;
        }

        private int code_ ;
        /**
         * <code>int32 code = 2;</code>
         */
        public int getCode() {
          return code_;
        }
        /**
         * <code>int32 code = 2;</code>
         */
        public Builder setCode(int value) {
          
          code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 code = 2;</code>
         */
        public Builder clearCode() {
          
          code_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object msg_ = "";
        /**
         * <code>string msg = 3;</code>
         */
        public java.lang.String getMsg() {
          java.lang.Object ref = msg_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            msg_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string msg = 3;</code>
         */
        public com.google.protobuf.ByteString
            getMsgBytes() {
          java.lang.Object ref = msg_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            msg_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string msg = 3;</code>
         */
        public Builder setMsg(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          msg_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string msg = 3;</code>
         */
        public Builder clearMsg() {
          
          msg_ = getDefaultInstance().getMsg();
          onChanged();
          return this;
        }
        /**
         * <code>string msg = 3;</code>
         */
        public Builder setMsgBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          msg_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:CommonProtocol.ResponseHeader)
      }

      // @@protoc_insertion_point(class_scope:CommonProtocol.ResponseHeader)
      private static final com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader();
      }

      public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ResponseHeader>
          PARSER = new com.google.protobuf.AbstractParser<ResponseHeader>() {
        @java.lang.Override
        public ResponseHeader parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseHeader(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ResponseHeader> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ResponseHeader> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int REQHEADER_FIELD_NUMBER = 1;
    private com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader reqHeader_;
    /**
     * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
     */
    public boolean hasReqHeader() {
      return reqHeader_ != null;
    }
    /**
     * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
     */
    public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader getReqHeader() {
      return reqHeader_ == null ? com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.getDefaultInstance() : reqHeader_;
    }
    /**
     * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
     */
    public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeaderOrBuilder getReqHeaderOrBuilder() {
      return getReqHeader();
    }

    public static final int RESHEADER_FIELD_NUMBER = 2;
    private com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader resHeader_;
    /**
     * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
     */
    public boolean hasResHeader() {
      return resHeader_ != null;
    }
    /**
     * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
     */
    public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader getResHeader() {
      return resHeader_ == null ? com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.getDefaultInstance() : resHeader_;
    }
    /**
     * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
     */
    public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeaderOrBuilder getResHeaderOrBuilder() {
      return getResHeader();
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 3;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (reqHeader_ != null) {
        output.writeMessage(1, getReqHeader());
      }
      if (resHeader_ != null) {
        output.writeMessage(2, getResHeader());
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (reqHeader_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getReqHeader());
      }
      if (resHeader_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResHeader());
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pingan.traffic.protocol.ProtocolModule.CommonProtocol)) {
        return super.equals(obj);
      }
      com.pingan.traffic.protocol.ProtocolModule.CommonProtocol other = (com.pingan.traffic.protocol.ProtocolModule.CommonProtocol) obj;

      boolean result = true;
      result = result && (hasReqHeader() == other.hasReqHeader());
      if (hasReqHeader()) {
        result = result && getReqHeader()
            .equals(other.getReqHeader());
      }
      result = result && (hasResHeader() == other.hasResHeader());
      if (hasResHeader()) {
        result = result && getResHeader()
            .equals(other.getResHeader());
      }
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasReqHeader()) {
        hash = (37 * hash) + REQHEADER_FIELD_NUMBER;
        hash = (53 * hash) + getReqHeader().hashCode();
      }
      if (hasResHeader()) {
        hash = (37 * hash) + RESHEADER_FIELD_NUMBER;
        hash = (53 * hash) + getResHeader().hashCode();
      }
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pingan.traffic.protocol.ProtocolModule.CommonProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *公共头
     * </pre>
     *
     * Protobuf type {@code CommonProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommonProtocol)
        com.pingan.traffic.protocol.ProtocolModule.CommonProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.class, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.Builder.class);
      }

      // Construct using com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (reqHeaderBuilder_ == null) {
          reqHeader_ = null;
        } else {
          reqHeader_ = null;
          reqHeaderBuilder_ = null;
        }
        if (resHeaderBuilder_ == null) {
          resHeader_ = null;
        } else {
          resHeader_ = null;
          resHeaderBuilder_ = null;
        }
        data_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pingan.traffic.protocol.ProtocolModule.internal_static_CommonProtocol_descriptor;
      }

      @java.lang.Override
      public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol getDefaultInstanceForType() {
        return com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.getDefaultInstance();
      }

      @java.lang.Override
      public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol build() {
        com.pingan.traffic.protocol.ProtocolModule.CommonProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol buildPartial() {
        com.pingan.traffic.protocol.ProtocolModule.CommonProtocol result = new com.pingan.traffic.protocol.ProtocolModule.CommonProtocol(this);
        if (reqHeaderBuilder_ == null) {
          result.reqHeader_ = reqHeader_;
        } else {
          result.reqHeader_ = reqHeaderBuilder_.build();
        }
        if (resHeaderBuilder_ == null) {
          result.resHeader_ = resHeader_;
        } else {
          result.resHeader_ = resHeaderBuilder_.build();
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pingan.traffic.protocol.ProtocolModule.CommonProtocol) {
          return mergeFrom((com.pingan.traffic.protocol.ProtocolModule.CommonProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pingan.traffic.protocol.ProtocolModule.CommonProtocol other) {
        if (other == com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.getDefaultInstance()) return this;
        if (other.hasReqHeader()) {
          mergeReqHeader(other.getReqHeader());
        }
        if (other.hasResHeader()) {
          mergeResHeader(other.getResHeader());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pingan.traffic.protocol.ProtocolModule.CommonProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pingan.traffic.protocol.ProtocolModule.CommonProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader reqHeader_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.Builder, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeaderOrBuilder> reqHeaderBuilder_;
      /**
       * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
       */
      public boolean hasReqHeader() {
        return reqHeaderBuilder_ != null || reqHeader_ != null;
      }
      /**
       * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
       */
      public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader getReqHeader() {
        if (reqHeaderBuilder_ == null) {
          return reqHeader_ == null ? com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.getDefaultInstance() : reqHeader_;
        } else {
          return reqHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
       */
      public Builder setReqHeader(com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader value) {
        if (reqHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reqHeader_ = value;
          onChanged();
        } else {
          reqHeaderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
       */
      public Builder setReqHeader(
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.Builder builderForValue) {
        if (reqHeaderBuilder_ == null) {
          reqHeader_ = builderForValue.build();
          onChanged();
        } else {
          reqHeaderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
       */
      public Builder mergeReqHeader(com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader value) {
        if (reqHeaderBuilder_ == null) {
          if (reqHeader_ != null) {
            reqHeader_ =
              com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.newBuilder(reqHeader_).mergeFrom(value).buildPartial();
          } else {
            reqHeader_ = value;
          }
          onChanged();
        } else {
          reqHeaderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
       */
      public Builder clearReqHeader() {
        if (reqHeaderBuilder_ == null) {
          reqHeader_ = null;
          onChanged();
        } else {
          reqHeader_ = null;
          reqHeaderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
       */
      public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.Builder getReqHeaderBuilder() {
        
        onChanged();
        return getReqHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
       */
      public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeaderOrBuilder getReqHeaderOrBuilder() {
        if (reqHeaderBuilder_ != null) {
          return reqHeaderBuilder_.getMessageOrBuilder();
        } else {
          return reqHeader_ == null ?
              com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.getDefaultInstance() : reqHeader_;
        }
      }
      /**
       * <code>.CommonProtocol.RequestHeader ReqHeader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.Builder, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeaderOrBuilder> 
          getReqHeaderFieldBuilder() {
        if (reqHeaderBuilder_ == null) {
          reqHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeader.Builder, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.RequestHeaderOrBuilder>(
                  getReqHeader(),
                  getParentForChildren(),
                  isClean());
          reqHeader_ = null;
        }
        return reqHeaderBuilder_;
      }

      private com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader resHeader_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.Builder, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeaderOrBuilder> resHeaderBuilder_;
      /**
       * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
       */
      public boolean hasResHeader() {
        return resHeaderBuilder_ != null || resHeader_ != null;
      }
      /**
       * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
       */
      public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader getResHeader() {
        if (resHeaderBuilder_ == null) {
          return resHeader_ == null ? com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.getDefaultInstance() : resHeader_;
        } else {
          return resHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
       */
      public Builder setResHeader(com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader value) {
        if (resHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resHeader_ = value;
          onChanged();
        } else {
          resHeaderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
       */
      public Builder setResHeader(
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.Builder builderForValue) {
        if (resHeaderBuilder_ == null) {
          resHeader_ = builderForValue.build();
          onChanged();
        } else {
          resHeaderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
       */
      public Builder mergeResHeader(com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader value) {
        if (resHeaderBuilder_ == null) {
          if (resHeader_ != null) {
            resHeader_ =
              com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.newBuilder(resHeader_).mergeFrom(value).buildPartial();
          } else {
            resHeader_ = value;
          }
          onChanged();
        } else {
          resHeaderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
       */
      public Builder clearResHeader() {
        if (resHeaderBuilder_ == null) {
          resHeader_ = null;
          onChanged();
        } else {
          resHeader_ = null;
          resHeaderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
       */
      public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.Builder getResHeaderBuilder() {
        
        onChanged();
        return getResHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
       */
      public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeaderOrBuilder getResHeaderOrBuilder() {
        if (resHeaderBuilder_ != null) {
          return resHeaderBuilder_.getMessageOrBuilder();
        } else {
          return resHeader_ == null ?
              com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.getDefaultInstance() : resHeader_;
        }
      }
      /**
       * <code>.CommonProtocol.ResponseHeader resHeader = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.Builder, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeaderOrBuilder> 
          getResHeaderFieldBuilder() {
        if (resHeaderBuilder_ == null) {
          resHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeader.Builder, com.pingan.traffic.protocol.ProtocolModule.CommonProtocol.ResponseHeaderOrBuilder>(
                  getResHeader(),
                  getParentForChildren(),
                  isClean());
          resHeader_ = null;
        }
        return resHeaderBuilder_;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 3;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 3;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 3;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommonProtocol)
    }

    // @@protoc_insertion_point(class_scope:CommonProtocol)
    private static final com.pingan.traffic.protocol.ProtocolModule.CommonProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pingan.traffic.protocol.ProtocolModule.CommonProtocol();
    }

    public static com.pingan.traffic.protocol.ProtocolModule.CommonProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommonProtocol>
        PARSER = new com.google.protobuf.AbstractParser<CommonProtocol>() {
      @java.lang.Override
      public CommonProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommonProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommonProtocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommonProtocol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.pingan.traffic.protocol.ProtocolModule.CommonProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommonProtocol_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonProtocol_RequestHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommonProtocol_RequestHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonProtocol_ResponseHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommonProtocol_ResponseHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ProtocolModule.proto\"\364\001\n\016CommonProtoco" +
      "l\0220\n\tReqHeader\030\001 \001(\0132\035.CommonProtocol.Re" +
      "questHeader\0221\n\tresHeader\030\002 \001(\0132\036.CommonP" +
      "rotocol.ResponseHeader\022\014\n\004data\030\003 \001(\t\0326\n\r" +
      "RequestHeader\022\n\n\002id\030\001 \001(\005\022\014\n\004code\030\002 \001(\005\022" +
      "\013\n\003msg\030\003 \001(\t\0327\n\016ResponseHeader\022\n\n\002id\030\001 \001" +
      "(\005\022\014\n\004code\030\002 \001(\005\022\013\n\003msg\030\003 \001(\tB-\n\033com.pin" +
      "gan.traffic.protocolB\016ProtocolModuleb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CommonProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommonProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommonProtocol_descriptor,
        new java.lang.String[] { "ReqHeader", "ResHeader", "Data", });
    internal_static_CommonProtocol_RequestHeader_descriptor =
      internal_static_CommonProtocol_descriptor.getNestedTypes().get(0);
    internal_static_CommonProtocol_RequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommonProtocol_RequestHeader_descriptor,
        new java.lang.String[] { "Id", "Code", "Msg", });
    internal_static_CommonProtocol_ResponseHeader_descriptor =
      internal_static_CommonProtocol_descriptor.getNestedTypes().get(1);
    internal_static_CommonProtocol_ResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommonProtocol_ResponseHeader_descriptor,
        new java.lang.String[] { "Id", "Code", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
